# Generated by Django 5.2.5 on 2025-08-23 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='headericon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appletouchicon', models.ImageField(upload_to='headericon/')),
                ('shortcuticon', models.ImageField(upload_to='headericon/')),
            ],
        ),
    ]
