# Generated by Django 5.2.5 on 2025-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_headericon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriesofthemonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='categoriesofthemonth/')),
                ('img1', models.ImageField(upload_to='categoriesofthemonth/')),
                ('img2', models.ImageField(upload_to='categoriesofthemonth/')),
            ],
        ),
    ]
