# Generated by Django 5.2.5 on 2025-08-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_categoriesofthemonth'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='subtitle',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='subtitle1',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='subtitle2',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='text1',
            field=models.TextField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='text2',
            field=models.TextField(default='a', max_length=200),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='title',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='title1',
            field=models.CharField(default='a', max_length=75),
        ),
        migrations.AddField(
            model_name='categoriesofthemonth',
            name='title2',
            field=models.CharField(default='a', max_length=75),
        ),
    ]
