# Generated by Django 5.2.5 on 2025-08-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_categoriesofthemonth_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoryandfeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_img1', models.ImageField(upload_to='categoryandfeature/')),
                ('cat_img2', models.ImageField(upload_to='categoryandfeature/')),
                ('cat_img3', models.ImageField(upload_to='categoryandfeature/')),
                ('cat_text1', models.CharField(max_length=50)),
                ('cat_text2', models.CharField(max_length=50)),
                ('cat_text3', models.CharField(max_length=50)),
                ('fea_img1', models.ImageField(upload_to='categoryandfeature/')),
                ('fea_img2', models.ImageField(upload_to='categoryandfeature/')),
                ('fea_img3', models.ImageField(upload_to='categoryandfeature/')),
                ('fea_text1', models.CharField(max_length=50)),
                ('fea_text2', models.CharField(max_length=50)),
                ('fea_text3', models.CharField(max_length=50)),
                ('fea_number1', models.IntegerField()),
                ('fea_number2', models.IntegerField()),
                ('fea_number3', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='heroandbrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_img', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img1', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img2', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img3', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img4', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img5', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img6', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img7', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img8', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img9', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img10', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img11', models.ImageField(upload_to='heroandbrand/')),
                ('brand_img12', models.ImageField(upload_to='heroandbrand/')),
            ],
        ),
    ]
