# Generated by Django 5.2.5 on 2025-08-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_categoryandfeature_heroandbrand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shophtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_img1', models.ImageField(upload_to='shopimages/')),
                ('shop_img2', models.ImageField(upload_to='shopimages/')),
                ('shop_img3', models.ImageField(upload_to='shopimages/')),
                ('shop_img4', models.ImageField(upload_to='shopimages/')),
                ('shop_img5', models.ImageField(upload_to='shopimages/')),
                ('shop_img6', models.ImageField(upload_to='shopimages/')),
                ('shop_img7', models.ImageField(upload_to='shopimages/')),
                ('shop_img8', models.ImageField(upload_to='shopimages/')),
                ('shop_img9', models.ImageField(upload_to='shopimages/')),
                ('brand_img1', models.ImageField(upload_to='shopimages/')),
                ('brand_img2', models.ImageField(upload_to='shopimages/')),
                ('brand_img3', models.ImageField(upload_to='shopimages/')),
                ('brand_img4', models.ImageField(upload_to='shopimages/')),
                ('brand_img5', models.ImageField(upload_to='shopimages/')),
                ('brand_img6', models.ImageField(upload_to='shopimages/')),
                ('brand_img7', models.ImageField(upload_to='shopimages/')),
                ('brand_img8', models.ImageField(upload_to='shopimages/')),
                ('brand_img9', models.ImageField(upload_to='shopimages/')),
                ('brand_img10', models.ImageField(upload_to='shopimages/')),
                ('brand_img11', models.ImageField(upload_to='shopimages/')),
                ('brand_img12', models.ImageField(upload_to='shopimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Shopsinglehtml',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img1', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img2', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img3', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img4', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img5', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img6', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img7', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img8', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img9', models.ImageField(upload_to='shopsingleimages/')),
                ('product_img10', models.ImageField(upload_to='shopsingleimages/')),
                ('shop_img1', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img2', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img3', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img4', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img5', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img6', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img7', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img8', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img9', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img10', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img11', models.ImageField(upload_to='shopsingleimage/')),
                ('shop_img12', models.ImageField(upload_to='shopsingleimage/')),
            ],
        ),
    ]
