# Generated by Django 5.2.5 on 2025-08-24 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_letstalk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribe',
            old_name='email',
            new_name='email2',
        ),
    ]
